version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: callhome
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  shared:
    image: call-home-shared
    build:
      context: ./shared/

  backend:
    build: backend/
    env_file:
      - ./backend/.env
    depends_on:
      - shared
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/callhome"

volumes:
  db-data:
