# This workflow will do a clean installation of node dependencies, cache/restore them, and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/

name: apps/super-app CI (push to master)

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    uses: ./.github/workflows/node_build.yml
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: 'Authenticate'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
    - name: 'Upload folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      working-directory: apps/super-app/
      with:
        path: '/build'
        destination: 'call-home-frontend'
    needs: build
  
